version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: employee_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: